### ISSUE TITLE
Plugin removed from WP Repo / patch vulnerability

### ISSUE THREAD

**Issue by razorfrog** [benhuson/list-pages-shortcode#11]
Hi - Will you be updating the List Pages Shortcode plugin to patch the vulnerability and get it back in the WP repo?

https://wordpress.org/plugins/list-pages-shortcode/

https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/list-pages-shortcode/list-pages-shortcode-174-authenticated-contributor-stored-cross-site-scripting-via-shortcode

Thank you!

**Comment by benhuson** [comment]
Yes, I have submitted a patch for review:
https://github.com/benhuson/list-pages-shortcode/commit/99eec560c6253b7c5b1aeb84f2e01c571d5529b9
